### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by MrRedBeard** [shvelo/musicxml_to_arduino#1]
Thanks for posting this. This helped me better understand the MXL format and gave me a head start on writing my own.

https://github.com/MrRedBeard/DotNet-MXL-Parsing-for-Arduino

**Comment by shvelo** [comment]
You're welcome, it took me a lot of trial and error to get it right since I don't know a lot about notes

**Comment by MrRedBeard** [comment]
Right! I know enough to get confused.

**Comment by MrRedBeard** [comment]
One more thing they gave you a shout out on HackADay http://hackaday.com/2017/07/23/play-it-again-arduino/
